export * from './assignroles.service';
import { AssignrolesService } from './assignroles.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './bar.service';
import { BarService } from './bar.service';
export * from './bars.service';
import { BarsService } from './bars.service';
export * from './calendar.service';
import { CalendarService } from './calendar.service';
export * from './competition.service';
import { CompetitionService } from './competition.service';
export * from './competitions.service';
import { CompetitionsService } from './competitions.service';
export * from './contact.service';
import { ContactService } from './contact.service';
export * from './cups.service';
import { CupsService } from './cups.service';
export * from './divisions.service';
import { DivisionsService } from './divisions.service';
export * from './finalday.service';
import { FinaldayService } from './finalday.service';
export * from './forum.service';
import { ForumService } from './forum.service';
export * from './leagues.service';
import { LeaguesService } from './leagues.service';
export * from './mailinglist.service';
import { MailinglistService } from './mailinglist.service';
export * from './matches.service';
import { MatchesService } from './matches.service';
export * from './news.service';
import { NewsService } from './news.service';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './recovery.service';
import { RecoveryService } from './recovery.service';
export * from './register.service';
import { RegisterService } from './register.service';
export * from './season.service';
import { SeasonService } from './season.service';
export * from './seasons.service';
import { SeasonsService } from './seasons.service';
export * from './sms.service';
import { SmsService } from './sms.service';
export * from './statistics.service';
import { StatisticsService } from './statistics.service';
export * from './tables.service';
import { TablesService } from './tables.service';
export * from './teaminscriptions.service';
import { TeaminscriptionsService } from './teaminscriptions.service';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './tournamentregistration.service';
import { TournamentregistrationService } from './tournamentregistration.service';
export * from './unassignroles.service';
import { UnassignrolesService } from './unassignroles.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AssignrolesService, AuthService, BarService, BarsService, CalendarService, CompetitionService, CompetitionsService, ContactService, CupsService, DivisionsService, FinaldayService, ForumService, LeaguesService, MailinglistService, MatchesService, NewsService, PaymentsService, RecoveryService, RegisterService, SeasonService, SeasonsService, SmsService, StatisticsService, TablesService, TeaminscriptionsService, TeamsService, TournamentregistrationService, UnassignrolesService, UsersService];
