/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { Register } from '../model/register';
import { RegisterResponse } from '../model/registerResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class RegisterService {

    protected basePath = 'https://localhost:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param accept Accept Header
     * @param userName 
     * @param firstName 
     * @param lastName 
     * @param displayName 
     * @param email 
     * @param password 
     * @param confirmPassword 
     * @param autoLogin 
     * @param errorView 
     * @param meta 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public register(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, observe?: 'body', reportProgress?: boolean): Observable<RegisterResponse>;
    public register(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RegisterResponse>>;
    public register(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RegisterResponse>>;
    public register(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accept === null || accept === undefined) {
            throw new Error('Required parameter accept was null or undefined when calling register.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (userName !== undefined && userName !== null) {
            queryParameters = queryParameters.set('UserName', <any>userName);
        }
        if (firstName !== undefined && firstName !== null) {
            queryParameters = queryParameters.set('FirstName', <any>firstName);
        }
        if (lastName !== undefined && lastName !== null) {
            queryParameters = queryParameters.set('LastName', <any>lastName);
        }
        if (displayName !== undefined && displayName !== null) {
            queryParameters = queryParameters.set('DisplayName', <any>displayName);
        }
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('Email', <any>email);
        }
        if (password !== undefined && password !== null) {
            queryParameters = queryParameters.set('Password', <any>password);
        }
        if (confirmPassword !== undefined && confirmPassword !== null) {
            queryParameters = queryParameters.set('ConfirmPassword', <any>confirmPassword);
        }
        if (autoLogin !== undefined && autoLogin !== null) {
            queryParameters = queryParameters.set('AutoLogin', <any>autoLogin);
        }
        if (errorView !== undefined && errorView !== null) {
            queryParameters = queryParameters.set('ErrorView', <any>errorView);
        }
        if (meta !== undefined && meta !== null) {
            queryParameters = queryParameters.set('Meta', <any>meta);
        }

        let headers = this.defaultHeaders;
        if (accept !== undefined && accept !== null) {
            headers = headers.set('Accept', String(accept));
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<RegisterResponse>(`${this.configuration.basePath}/register`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param accept Accept Header
     * @param userName 
     * @param firstName 
     * @param lastName 
     * @param displayName 
     * @param email 
     * @param password 
     * @param confirmPassword 
     * @param autoLogin 
     * @param errorView 
     * @param meta 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerDELETE(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, observe?: 'body', reportProgress?: boolean): Observable<RegisterResponse>;
    public registerDELETE(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RegisterResponse>>;
    public registerDELETE(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RegisterResponse>>;
    public registerDELETE(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accept === null || accept === undefined) {
            throw new Error('Required parameter accept was null or undefined when calling registerDELETE.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (userName !== undefined && userName !== null) {
            queryParameters = queryParameters.set('UserName', <any>userName);
        }
        if (firstName !== undefined && firstName !== null) {
            queryParameters = queryParameters.set('FirstName', <any>firstName);
        }
        if (lastName !== undefined && lastName !== null) {
            queryParameters = queryParameters.set('LastName', <any>lastName);
        }
        if (displayName !== undefined && displayName !== null) {
            queryParameters = queryParameters.set('DisplayName', <any>displayName);
        }
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('Email', <any>email);
        }
        if (password !== undefined && password !== null) {
            queryParameters = queryParameters.set('Password', <any>password);
        }
        if (confirmPassword !== undefined && confirmPassword !== null) {
            queryParameters = queryParameters.set('ConfirmPassword', <any>confirmPassword);
        }
        if (autoLogin !== undefined && autoLogin !== null) {
            queryParameters = queryParameters.set('AutoLogin', <any>autoLogin);
        }
        if (errorView !== undefined && errorView !== null) {
            queryParameters = queryParameters.set('ErrorView', <any>errorView);
        }
        if (meta !== undefined && meta !== null) {
            queryParameters = queryParameters.set('Meta', <any>meta);
        }

        let headers = this.defaultHeaders;
        if (accept !== undefined && accept !== null) {
            headers = headers.set('Accept', String(accept));
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.delete<RegisterResponse>(`${this.configuration.basePath}/register`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param accept Accept Header
     * @param userName 
     * @param firstName 
     * @param lastName 
     * @param displayName 
     * @param email 
     * @param password 
     * @param confirmPassword 
     * @param autoLogin 
     * @param errorView 
     * @param meta 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerPOST(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, body?: Register, observe?: 'body', reportProgress?: boolean): Observable<RegisterResponse>;
    public registerPOST(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, body?: Register, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RegisterResponse>>;
    public registerPOST(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, body?: Register, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RegisterResponse>>;
    public registerPOST(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, body?: Register, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accept === null || accept === undefined) {
            throw new Error('Required parameter accept was null or undefined when calling registerPOST.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (userName !== undefined && userName !== null) {
            queryParameters = queryParameters.set('UserName', <any>userName);
        }
        if (firstName !== undefined && firstName !== null) {
            queryParameters = queryParameters.set('FirstName', <any>firstName);
        }
        if (lastName !== undefined && lastName !== null) {
            queryParameters = queryParameters.set('LastName', <any>lastName);
        }
        if (displayName !== undefined && displayName !== null) {
            queryParameters = queryParameters.set('DisplayName', <any>displayName);
        }
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('Email', <any>email);
        }
        if (password !== undefined && password !== null) {
            queryParameters = queryParameters.set('Password', <any>password);
        }
        if (confirmPassword !== undefined && confirmPassword !== null) {
            queryParameters = queryParameters.set('ConfirmPassword', <any>confirmPassword);
        }
        if (autoLogin !== undefined && autoLogin !== null) {
            queryParameters = queryParameters.set('AutoLogin', <any>autoLogin);
        }
        if (errorView !== undefined && errorView !== null) {
            queryParameters = queryParameters.set('ErrorView', <any>errorView);
        }
        if (meta !== undefined && meta !== null) {
            queryParameters = queryParameters.set('Meta', <any>meta);
        }

        let headers = this.defaultHeaders;
        if (accept !== undefined && accept !== null) {
            headers = headers.set('Accept', String(accept));
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<RegisterResponse>(`${this.configuration.basePath}/register`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param accept Accept Header
     * @param userName 
     * @param firstName 
     * @param lastName 
     * @param displayName 
     * @param email 
     * @param password 
     * @param confirmPassword 
     * @param autoLogin 
     * @param errorView 
     * @param meta 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerPUT(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, body?: Register, observe?: 'body', reportProgress?: boolean): Observable<RegisterResponse>;
    public registerPUT(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, body?: Register, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RegisterResponse>>;
    public registerPUT(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, body?: Register, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RegisterResponse>>;
    public registerPUT(accept: 'application/json', userName?: string, firstName?: string, lastName?: string, displayName?: string, email?: string, password?: string, confirmPassword?: string, autoLogin?: boolean, errorView?: string, meta?: string, body?: Register, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accept === null || accept === undefined) {
            throw new Error('Required parameter accept was null or undefined when calling registerPUT.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (userName !== undefined && userName !== null) {
            queryParameters = queryParameters.set('UserName', <any>userName);
        }
        if (firstName !== undefined && firstName !== null) {
            queryParameters = queryParameters.set('FirstName', <any>firstName);
        }
        if (lastName !== undefined && lastName !== null) {
            queryParameters = queryParameters.set('LastName', <any>lastName);
        }
        if (displayName !== undefined && displayName !== null) {
            queryParameters = queryParameters.set('DisplayName', <any>displayName);
        }
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('Email', <any>email);
        }
        if (password !== undefined && password !== null) {
            queryParameters = queryParameters.set('Password', <any>password);
        }
        if (confirmPassword !== undefined && confirmPassword !== null) {
            queryParameters = queryParameters.set('ConfirmPassword', <any>confirmPassword);
        }
        if (autoLogin !== undefined && autoLogin !== null) {
            queryParameters = queryParameters.set('AutoLogin', <any>autoLogin);
        }
        if (errorView !== undefined && errorView !== null) {
            queryParameters = queryParameters.set('ErrorView', <any>errorView);
        }
        if (meta !== undefined && meta !== null) {
            queryParameters = queryParameters.set('Meta', <any>meta);
        }

        let headers = this.defaultHeaders;
        if (accept !== undefined && accept !== null) {
            headers = headers.set('Accept', String(accept));
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<RegisterResponse>(`${this.configuration.basePath}/register`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
