/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { EinteilungLeagueDto } from '../model/einteilungLeagueDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class SeasonService {

    protected basePath = 'https://localhost:5001';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param accept Accept Header
     * @param competitionId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public einteilungen(accept: 'application/json', competitionId: number, observe?: 'body', reportProgress?: boolean): Observable<EinteilungLeagueDto>;
    public einteilungen(accept: 'application/json', competitionId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EinteilungLeagueDto>>;
    public einteilungen(accept: 'application/json', competitionId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EinteilungLeagueDto>>;
    public einteilungen(accept: 'application/json', competitionId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accept === null || accept === undefined) {
            throw new Error('Required parameter accept was null or undefined when calling einteilungen.');
        }
        if (competitionId === null || competitionId === undefined) {
            throw new Error('Required parameter competitionId was null or undefined when calling einteilungen.');
        }

        let headers = this.defaultHeaders;
        if (accept !== undefined && accept !== null) {
            headers = headers.set('Accept', String(accept));
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<EinteilungLeagueDto>(`${this.configuration.basePath}/season/einteilungen/${encodeURIComponent(String(competitionId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets all standings for the current seasons finalday
     * Gets all standings for the current seasons finalday
     * @param accept Accept Header
     * @param seasonId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFinalDayStandings(accept: 'application/json', seasonId?: number, observe?: 'body', reportProgress?: boolean): Observable<object>;
    public getFinalDayStandings(accept: 'application/json', seasonId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<object>>;
    public getFinalDayStandings(accept: 'application/json', seasonId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<object>>;
    public getFinalDayStandings(accept: 'application/json', seasonId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accept === null || accept === undefined) {
            throw new Error('Required parameter accept was null or undefined when calling getFinalDayStandings.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (seasonId !== undefined && seasonId !== null) {
            queryParameters = queryParameters.set('SeasonId', <any>seasonId);
        }

        let headers = this.defaultHeaders;
        if (accept !== undefined && accept !== null) {
            headers = headers.set('Accept', String(accept));
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<object>(`${this.configuration.basePath}/season/current/finaldaystandings`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets all standings for the current seasons finalday
     * Gets all standings for the current seasons finalday
     * @param accept Accept Header
     * @param seasonId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFinalDayStandingsGET(accept: 'application/json', seasonId: number, observe?: 'body', reportProgress?: boolean): Observable<object>;
    public getFinalDayStandingsGET(accept: 'application/json', seasonId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<object>>;
    public getFinalDayStandingsGET(accept: 'application/json', seasonId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<object>>;
    public getFinalDayStandingsGET(accept: 'application/json', seasonId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accept === null || accept === undefined) {
            throw new Error('Required parameter accept was null or undefined when calling getFinalDayStandingsGET.');
        }
        if (seasonId === null || seasonId === undefined) {
            throw new Error('Required parameter seasonId was null or undefined when calling getFinalDayStandingsGET.');
        }

        let headers = this.defaultHeaders;
        if (accept !== undefined && accept !== null) {
            headers = headers.set('Accept', String(accept));
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<object>(`${this.configuration.basePath}/season/${encodeURIComponent(String(seasonId))}/finaldaystandings`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
