/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * CompetitionRegisterRequest
 */
export interface CompetitionRegisterRequest { 
    /**
     * Score of the Home Team
     */
    name: string;
    wishPlayDay?: string;
    /**
     * Score of the Home Team
     */
    seasonAmbition?: string;
}

