/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ExtendedMatchDto
 */
export interface ExtendedMatchDto { 
    id?: number;
    homeTeamId?: number;
    guestTeamId?: number;
    homeTeamScore?: number;
    guestTeamScore?: number;
    barId?: number;
    playDate?: Date;
    registerDate?: Date;
    resultDate?: Date;
    leagueId?: number;
    cupId?: number;
    cupRound?: number;
    isWinnerBracketGame?: boolean;
    roundOrder?: number;
    homeTeamName?: string;
    guestTeamName?: string;
    homePlayer1Id?: number;
    homePlayer2Id?: number;
    guestPlayer1Id?: number;
    guestPlayer2Id?: number;
    barName?: string;
    cupName?: string;
    competitionId?: number;
    seasonId?: number;
    isFreeTicket?: boolean;
}

