/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';
import { FinalDayCompetitionDto } from './finalDayCompetitionDto';


/**
 * FinalDayPlayerInCompetitionDto
 */
export interface FinalDayPlayerInCompetitionDto { 
    id?: number;
    player?: UserDto;
    activeFinalDayCompetitions?: Array<FinalDayCompetitionDto>;
    isActive?: boolean;
}

