/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';
import { ForumThreadDto } from './forumThreadDto';


/**
 * ForumPostDto
 */
export interface ForumPostDto { 
    id?: number;
    userAuthId?: number;
    userAuth?: UserDto;
    forumThreadId?: number;
    forumThread?: ForumThreadDto;
    text?: string;
    date?: Date;
}

