/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamInGroupViewDto } from './teamInGroupViewDto';
import { FinalDayCompetitionDto } from './finalDayCompetitionDto';


/**
 * GroupDto
 */
export interface GroupDto { 
    id?: number;
    number?: number;
    finalDayCompetitionId?: number;
    finalyDayCompetition?: FinalDayCompetitionDto;
    teams?: Array<TeamInGroupViewDto>;
    numberOfSuccessor?: number;
}

