/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompetitionDto } from './competitionDto';
import { TableEntryViewDto } from './tableEntryViewDto';


/**
 * LeagueDto
 */
export interface LeagueDto { 
    seasonId?: string;
    number?: number;
    group?: number;
    tableEntries?: Array<TableEntryViewDto>;
    competition?: CompetitionDto;
    leagueMatchCreationMode?: string;
    name?: string;
    id?: number;
}

