/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamDto } from './teamDto';
import { NameDto } from './nameDto';


/**
 * MatchDto
 */
export interface MatchDto { 
    id?: string;
    homeTeam?: TeamDto;
    guestTeam?: TeamDto;
    homeTeamScore?: number;
    guestTeamScore?: number;
    bar?: NameDto;
    playDate?: Date;
    registerDate?: Date;
    resultDate?: Date;
    cupRound?: number;
}

