/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Register
 */
export interface Register { 
    userName?: string;
    firstName?: string;
    lastName?: string;
    displayName?: string;
    email?: string;
    password?: string;
    confirmPassword?: string;
    autoLogin?: boolean;
    errorView?: string;
    /**
     * Dictionary<String,String>
     */
    meta?: { [key: string]: string; };
}

