/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * TableEntryViewDto
 */
export interface TableEntryViewDto { 
    id?: number;
    leagueId?: number;
    isTeamForfaitOut?: boolean;
    teamId?: number;
    gamesPlayed?: number;
    gamesNotPlayed?: number;
    gamesWon?: number;
    gamesWonExtension?: number;
    gamesDraw?: number;
    gamesLost?: number;
    gamesLostExtension?: number;
    points?: number;
    setsWon?: number;
    setsLost?: number;
    rank?: number;
    estimatedRank?: number;
    teamName?: string;
    player1FirstName?: string;
    player1LastName?: string;
    player2FirstName?: string;
    player2LastName?: string;
    plusMinus?: number;
    qualifiedForFinalDay?: string;
    qualifiedForFinalDayComment?: string;
}

