/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


/**
 * TeamInscriptionDto
 */
export interface TeamInscriptionDto { 
    competitionId?: number;
    player1Id?: number;
    player1?: UserDto;
    player2Id?: number;
    player2?: UserDto;
    wishLeague?: number;
    seasonAmbition?: string;
    barId?: number;
    barName?: string;
    assignedLeagueId?: number;
    name?: string;
    id?: number;
}

