/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * TeamInGroupViewDto
 */
export interface TeamInGroupViewDto { 
    id?: number;
    groupId?: number;
    teamName?: string;
    teamId?: number;
    settlement?: number;
    player1FirstName?: string;
    player1LastName?: string;
    player2FirstName?: string;
    player2LastName?: string;
}

