/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * UpdateUserProfileRequest
 */
export interface UpdateUserProfileRequest { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    phoneNumber?: string;
    divisionZuerich?: boolean;
    divisionStGallen?: boolean;
    divisionLuzern?: boolean;
    divisionWinti?: boolean;
}

