/**
 * Fordere WebService Console
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * UpdateTeamRequest
 */
export interface UpdateTeamRequest { 
    id?: number;
    barId?: number;
    name?: string;
    seasonAmbition?: string;
    isForfaitOut?: boolean;
    player1Id?: number;
    player2Id?: number;
    wishPlayDay?: string;
    qualifiedForFinalDay?: string;
    qualifiedForFinalDayComment?: string;
}

